var GAME_LEVELS = [
  ["                                                                                ",
   "                                                                                ",
   "                                                                                ",
   "                                                                                ",
   "                                                                                ",
   "                                                                                ",
   "                                                                                ",
   "                                                   xx      xx                   ",
   "                                    o o      xx                                 ",
   "                                                                                ",
   "           x    xxxx                                     x!!!!!xx               ",
   "           x!!!!x                                        xxx!!!xxx          xx  ",
   "  xx       xxxxxx      xxx          xx    o o            xxxxxxxxx           x  ",
   "  x                o                                                         x  ",
   "  x      ^          ^                               xxxxxx                 o x  ",
   "  x                xx               xxx                                      x  ",
   "  x  @     u                                                                  x  ",
   "  xxxxxxxxxxx                 x!y! xxx    xxxxxxxxxxxxx     xx       xxxxxxxxx  ",
   "            x                 x!!!x                                x            ",
   "           xx                 xxxxx                              xxx            ",
   "           x             u                 xxxxx                xx              ",
   "           xxx       o   xx            xxxxx   x                x               ",
   "              !!yy!yyyy!!xxx          x        xxxxx!!yy!!!xxxxx                ",
   "         !!!!!!!!!!!!!!!!!xxxxxxxxxxxxx               xxxxxx                    ",
   "	!!!!!!!!!!!!!!!!	        												"],
	
	
	
  ["                                                                  yyyyyyyy                                   x!x  ",
   "                                                                 yyyyyyyyyyy                                      ",
   "                                                               yyyyyyyyyyyyy                                      ",
   "                                                              yyyyyyyyyyyyyyyyy                                   ",
   "                                                            yyyyyyyyyyyyyyyyyyyyy                                 ",
   "                                                              yyyyyy     yyyyy                               x!x  ",
   "                                                            yyyyyyy  ooo  yyyyyy                             x!x  ",
   "                                               xx           yyyyyyy       yyyyy                              x!x  ",
   "                                                x             yyyyyy                     o   o               x!x  ",
   "                                                        x       yyyyyyy                                     xx!x  ",
   "                                    x   xx               x          xx                    xxxxxxxxxxxxxx    x!!x  ",
   "                                                 xvx         x      xx xx   o                   !!!!!!!!!!!!!!xx  ",
   "                                    x    xx                         xx      xx     xx      xxxxxxxxxxxxxxxxxxxxx  ",
   "                                                              xx!!!!xx!!!!!xx            v                        ",
   "                                    x                          xxxx!xx!!xxxx                                      ",
   "                                               x     x            xxxxxxx x                  xxx                  ",
   "                                    x       xx          x        xx   x    x        x x         x x               ",
   "                                    x      x                     x     x           x         x                    ",
   "                xvx                 x     x       x                                xx        x                    ",
   "                x!x               o x          xx   xx                             x         x                    ",
   "                x!x  o              x          x!!!! x      o  o   xx         xx   x         x                    ",
   "               xxv xxx          x   x          x !!! x                             x     xx  x                    ",
   "              xx     xx        xx   x   x xxxx x !!!!x     xxxx              xxxxxxxxx       x                    ",
   "                      x         x o x          x !!!!x                     o x               x                    ",
   "     @           xx             x   x          x !!! x              xx   x   x               x                    ",
   "    xxx                    x!! xx   x xxxxx    x !!!!x                   x       xxxxxx      x                    ",
   "    x x                    x!!!xx   xx         x!!!!! x                           x x         x                   ",
   "!!!!x x      x              xxxx               xx !!! x!!!!!!!!!!                 x x         x                   ",
   "!!!!x x!!yy!!x                          xxxxxxxx  == x!!!!!!!xx! xxxxxxxxx    xxxx xx  o o  xx                    ",
   "!!!!x x!!!!!!x  xx                o                 xx!!!!!!xx !         x                 xx                     ",
   "!!!!x x!!!!!!x               x                     xx!!!!!!xx  !         xxxxxxxxx   xxxxxxx                      ",
   "!!!!x x!!!!!!x    xx   xxxxxxxx       xxxxxxxxxxxxxx!!!!!!xx   !                                                  ",
   "!!!!x x!!!!!!x         x!!!!!!xxxxxxxxx!!!!!!!!!!!!!!!!!!xx    !                                                  ",
   "!!!!x x!!!!!!x   ===   x!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!xx     !                                                  "],
	
	

   ["                                                                  yyyyyyyy                                  x!x  ",
   "                                                                 yyyyyyyyyyy                   xxx!x              ",
   "                                        o     y                yyyyyyyyyyyyyo                o x!!xx              ",
   "                                 y      yy  y                 yyyyyyyyyyyyyyyyy         x!!!!xx!!!xx              ",
   "                                   y  yyyyyy  y             yyyyyyyyyyyyyyyyyyyyy       x!xxxxxxxxxx              ",
   "               yyyy                yyyyyyyyyy y             y yyyyyyyyyyyyyyyy          x!x                  x!x  ",
   "             yyyyyy   yyy         y   yyyyyy   y           y                   y         v                   x!x  ",
   "          yyyyyyyyy     yy           y  xx     xx                             y      xx          o o         x!x  ",
   "         yyyyyyyoo       yy        y    xx      x                    yy                                      x!x  ",
   "         yyyyyyy                   yy   xx                       yyyyy                                      xx!x  ",
   "  @        yyyyyyyyyyy              y   xx               x      y yyxx           xx        xxxxxxxxxxxxx    x!!x  ",
   "  xx         yyyyyy                 y    =       xvx                xxo                         !!!!!!!!!!!!!!xx  ",
   "               xx               yyyy     xx                         xxxxx          xx        xxxxxxxxxxxxxxxxvxx  ",
   "               xx                                             xx!!!!xx!!!!!xxx                                    ",
   "               xx                                              xxxx!xx!!xxxx                          o           ",
   "               xx o                 y        o x                  xxxxxxx x                          xxx          ",
   "             x    x                 y       xx          x x      xx   xxx                                         ",
   "  xxxxxxxxxxxxxxxxxxxxxxxxxxxxx                                       xxxx       xxxxxxx   xxxxxxxxxxxxxxxxx      ",
   "                              x                   |                   xxx         =         !!!!!!!!!!!!!!!!!!!!!!",
   "                              xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx "],
	
	["                                                                                                                ",
	 "                     y   y   yy    y   y        y     y    y   y   y    y                                       ",
	 "                      y y   y   y  y   y         y   y y  y    y   y y  y                                       ",
	 "                       y    y   y  y   y          yyy  yyy     y   y  yy                                        ",
	 "                       y     yy     yyy                                                                         "],
	

];

if (typeof module != "undefined" && module.exports)
  module.exports = GAME_LEVELS;
